/**
 * Static mock salon data — used as fallback when Firebase is not configured
 * or credentials are missing. Mirrors the shape of the seed data exactly.
 */
import type { Salon } from '@/types'
import { Timestamp } from 'firebase/firestore'

const now = Timestamp.now()

export const MOCK_SALONS: Salon[] = [
  {
    id: 'salon-001',
    name: 'Glow Studio Bandra',
    slug: 'glow-studio-bandra',
    city: 'Mumbai',
    area: 'Bandra West',
    coordinates: { latitude: 19.0596, longitude: 72.8295 },
    coverImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800',
    gallery: [],
    priceRange: 'mid',
    rating: 4.7,
    reviewCount: 234,
    tags: ['hair-color', 'balayage', 'keratin', 'bridal'],
    isVerified: true,
    ownerId: 'owner-001',
    openingHours: {},
    createdAt: now,
    services: [
      { id: 'svc-001-1', name: 'Balayage', category: 'hair', duration: 120, price: 3500, description: 'Sun-kissed balayage technique' },
      { id: 'svc-001-2', name: 'Keratin Treatment', category: 'hair', duration: 90, price: 4000, description: 'Frizz-free keratin smoothing' },
      { id: 'svc-001-3', name: 'Bridal Makeup', category: 'bridal', duration: 180, price: 8000, description: 'Complete bridal look with trial' },
    ],
  },
  {
    id: 'salon-002',
    name: 'Luxe Hair Andheri',
    slug: 'luxe-hair-andheri',
    city: 'Mumbai',
    area: 'Andheri West',
    coordinates: { latitude: 19.1136, longitude: 72.8697 },
    coverImage: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800',
    gallery: [],
    priceRange: 'luxury',
    rating: 4.9,
    reviewCount: 412,
    tags: ['luxury', 'hair-spa', 'ombre', 'extensions'],
    isVerified: true,
    ownerId: 'owner-001',
    openingHours: {},
    createdAt: now,
    services: [
      { id: 'svc-002-1', name: 'Hair Extensions', category: 'hair', duration: 240, price: 12000, description: 'Premium clip-in extensions' },
      { id: 'svc-002-2', name: 'Hair Spa', category: 'hair', duration: 60, price: 1500, description: 'Deep conditioning spa treatment' },
      { id: 'svc-002-3', name: 'Ombre Coloring', category: 'hair', duration: 150, price: 5000, description: 'Gradient ombre effect' },
    ],
  },
  {
    id: 'salon-003',
    name: 'Blush Beauty Juhu',
    slug: 'blush-beauty-juhu',
    city: 'Mumbai',
    area: 'Juhu',
    coordinates: { latitude: 19.1075, longitude: 72.8263 },
    coverImage: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=800',
    gallery: [],
    priceRange: 'mid',
    rating: 4.5,
    reviewCount: 187,
    tags: ['skin', 'facial', 'cleanup', 'waxing'],
    isVerified: true,
    ownerId: 'owner-001',
    openingHours: {},
    createdAt: now,
    services: [
      { id: 'svc-003-1', name: 'Gold Facial', category: 'skin', duration: 60, price: 1200, description: 'Anti-aging gold facial' },
      { id: 'svc-003-2', name: 'Full Body Wax', category: 'skin', duration: 90, price: 800, description: 'Smooth full body waxing' },
      { id: 'svc-003-3', name: 'Clean-up', category: 'skin', duration: 45, price: 500, description: 'Basic skin clean-up' },
    ],
  },
  {
    id: 'salon-004',
    name: 'The Nail Lounge Colaba',
    slug: 'nail-lounge-colaba',
    city: 'Mumbai',
    area: 'Colaba',
    coordinates: { latitude: 18.9067, longitude: 72.8147 },
    coverImage: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800',
    gallery: [],
    priceRange: 'mid',
    rating: 4.6,
    reviewCount: 320,
    tags: ['nails', 'gel-nails', 'nail-art', 'manicure', 'soft-gel', 'pedicure'],
    isVerified: true,
    ownerId: 'owner-001',
    openingHours: {},
    createdAt: now,
    services: [
      { id: 'svc-004-1', name: 'Gel Manicure', category: 'nails', duration: 45, price: 800, description: 'Long-lasting gel polish manicure' },
      { id: 'svc-004-2', name: 'Soft Gel Extensions', category: 'nails', duration: 90, price: 1800, description: 'Natural-looking soft gel nail extensions' },
      { id: 'svc-004-3', name: 'Nail Art (per nail)', category: 'nails', duration: 60, price: 600, description: 'Custom nail art designs' },
      { id: 'svc-004-4', name: 'Pedicure', category: 'nails', duration: 45, price: 700, description: 'Relaxing foot pedicure' },
    ],
  },
  {
    id: 'salon-005',
    name: 'Swagger Grooming Powai',
    slug: 'swagger-grooming-powai',
    city: 'Mumbai',
    area: 'Powai',
    coordinates: { latitude: 19.1197, longitude: 72.9051 },
    coverImage: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800',
    gallery: [],
    priceRange: 'budget',
    rating: 4.4,
    reviewCount: 156,
    tags: ['grooming', 'haircut', 'beard', 'mens'],
    isVerified: true,
    ownerId: 'owner-001',
    openingHours: {},
    createdAt: now,
    services: [
      { id: 'svc-005-1', name: 'Haircut & Style', category: 'grooming', duration: 30, price: 400, description: "Professional men's haircut" },
      { id: 'svc-005-2', name: 'Beard Trim', category: 'grooming', duration: 20, price: 200, description: 'Precision beard shaping' },
      { id: 'svc-005-3', name: 'Head Massage', category: 'spa', duration: 30, price: 300, description: 'Relaxing scalp massage' },
    ],
  },
  {
    id: 'salon-006',
    name: 'Aura Bridal Studio Bandra',
    slug: 'aura-bridal-bandra',
    city: 'Mumbai',
    area: 'Bandra East',
    coordinates: { latitude: 19.0544, longitude: 72.8407 },
    coverImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800',
    gallery: [],
    priceRange: 'luxury',
    rating: 4.8,
    reviewCount: 98,
    tags: ['bridal', 'mehendi', 'makeup', 'draping'],
    isVerified: true,
    ownerId: 'owner-001',
    openingHours: {},
    createdAt: now,
    services: [
      { id: 'svc-006-1', name: 'Bridal Package', category: 'bridal', duration: 300, price: 25000, description: 'Complete bridal package with trial' },
      { id: 'svc-006-2', name: 'Mehendi Design', category: 'bridal', duration: 120, price: 3000, description: 'Intricate bridal mehendi' },
    ],
  },
  {
    id: 'salon-007',
    name: 'Glow Up Versova',
    slug: 'glow-up-versova',
    city: 'Mumbai',
    area: 'Versova',
    coordinates: { latitude: 19.1300, longitude: 72.8185 },
    coverImage: 'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800',
    gallery: [],
    priceRange: 'budget',
    rating: 4.3,
    reviewCount: 89,
    tags: ['hair-color', 'highlights', 'hair-spa', 'waxing'],
    isVerified: true,
    ownerId: 'owner-001',
    openingHours: {},
    createdAt: now,
    services: [
      { id: 'svc-007-1', name: 'Global Hair Color', category: 'hair', duration: 90, price: 1500, description: 'Full head global color' },
      { id: 'svc-007-2', name: 'Highlights', category: 'hair', duration: 120, price: 2000, description: 'Foil highlights' },
    ],
  },
  {
    id: 'salon-008',
    name: 'Serenity Spa Malad',
    slug: 'serenity-spa-malad',
    city: 'Mumbai',
    area: 'Malad West',
    coordinates: { latitude: 19.1871, longitude: 72.8481 },
    coverImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800',
    gallery: [],
    priceRange: 'mid',
    rating: 4.5,
    reviewCount: 201,
    tags: ['spa', 'massage', 'facial', 'skin'],
    isVerified: true,
    ownerId: 'owner-001',
    openingHours: {},
    createdAt: now,
    services: [
      { id: 'svc-008-1', name: 'Full Body Massage', category: 'spa', duration: 90, price: 2500, description: 'Swedish full body massage' },
      { id: 'svc-008-2', name: 'Anti-Aging Facial', category: 'skin', duration: 75, price: 1800, description: 'Premium anti-aging treatment' },
    ],
  },
  {
    id: 'salon-009',
    name: 'Curl Cult Khar',
    slug: 'curl-cult-khar',
    city: 'Mumbai',
    area: 'Khar West',
    coordinates: { latitude: 19.0728, longitude: 72.8376 },
    coverImage: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=800',
    gallery: [],
    priceRange: 'mid',
    rating: 4.6,
    reviewCount: 143,
    tags: ['curly-hair', 'hair-color', 'treatment', 'balayage'],
    isVerified: true,
    ownerId: 'owner-001',
    openingHours: {},
    createdAt: now,
    services: [
      { id: 'svc-009-1', name: 'Curly Cut', category: 'hair', duration: 75, price: 1200, description: 'Specialist curly hair cut' },
      { id: 'svc-009-2', name: 'Deep Conditioning', category: 'hair', duration: 60, price: 900, description: 'Moisture-rich deep conditioning' },
    ],
  },
  {
    id: 'salon-010',
    name: 'Naked Beauty Dadar',
    slug: 'naked-beauty-dadar',
    city: 'Mumbai',
    area: 'Dadar West',
    coordinates: { latitude: 19.0176, longitude: 72.8433 },
    coverImage: 'https://images.unsplash.com/photo-1559599101-f09722fb4948?w=800',
    gallery: [],
    priceRange: 'budget',
    rating: 4.2,
    reviewCount: 267,
    tags: ['waxing', 'threading', 'cleanup', 'manicure', 'acrylic-nails'],
    isVerified: true,
    ownerId: 'owner-001',
    openingHours: {},
    createdAt: now,
    services: [
      { id: 'svc-010-1', name: 'Eyebrow Threading', category: 'skin', duration: 15, price: 80, description: 'Precise eyebrow threading' },
      { id: 'svc-010-2', name: 'Upper Lip Wax', category: 'skin', duration: 10, price: 60, description: 'Quick upper lip wax' },
      { id: 'svc-010-3', name: 'Acrylic Nail Extensions', category: 'nails', duration: 75, price: 1200, description: 'Durable acrylic nail extensions' },
      { id: 'svc-010-4', name: 'Basic Manicure', category: 'nails', duration: 30, price: 250, description: 'Classic manicure' },
    ],
  },
  {
    id: 'salon-011',
    name: 'Nail Canvas Santacruz',
    slug: 'nail-canvas-santacruz',
    city: 'Mumbai',
    area: 'Santacruz West',
    coordinates: { latitude: 19.0821, longitude: 72.8415 },
    coverImage: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800',
    gallery: [],
    priceRange: 'mid',
    rating: 4.7,
    reviewCount: 178,
    tags: ['nails', 'soft-gel', 'gel-nails', 'nail-art', 'chrome-nails', 'ombre-nails'],
    isVerified: true,
    ownerId: 'owner-001',
    openingHours: {},
    createdAt: now,
    services: [
      { id: 'svc-011-1', name: 'Soft Gel Manicure', category: 'nails', duration: 60, price: 1200, description: 'Builder gel overlay for natural strength' },
      { id: 'svc-011-2', name: 'Chrome Nail Art', category: 'nails', duration: 75, price: 1500, description: 'Mirror-finish chrome powder nail art' },
      { id: 'svc-011-3', name: 'Ombre Nails', category: 'nails', duration: 90, price: 1800, description: 'Gradient ombre nail design' },
      { id: 'svc-011-4', name: 'Gel Pedicure', category: 'nails', duration: 50, price: 900, description: 'Long-lasting gel pedicure' },
    ],
  },
  {
    id: 'salon-012',
    name: 'The Polish Bar Worli',
    slug: 'polish-bar-worli',
    city: 'Mumbai',
    area: 'Worli',
    coordinates: { latitude: 19.0144, longitude: 72.8192 },
    coverImage: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800',
    gallery: [],
    priceRange: 'luxury',
    rating: 4.8,
    reviewCount: 245,
    tags: ['nails', 'gel-nails', 'acrylic-nails', 'nail-art', 'bridal-nails', 'hard-gel'],
    isVerified: true,
    ownerId: 'owner-001',
    openingHours: {},
    createdAt: now,
    services: [
      { id: 'svc-012-1', name: 'Hard Gel Extensions', category: 'nails', duration: 120, price: 3500, description: 'Durable hard gel nail extensions with top coat' },
      { id: 'svc-012-2', name: 'Acrylic Full Set', category: 'nails', duration: 90, price: 2500, description: 'Classic acrylic nail set with gel overlay' },
      { id: 'svc-012-3', name: 'Bridal Nail Package', category: 'nails', duration: 180, price: 6000, description: 'Complete bridal nail prep and art' },
      { id: 'svc-012-4', name: '3D Nail Art', category: 'nails', duration: 120, price: 2000, description: 'Sculptural 3D nail art designs' },
    ],
  },
]

/** Check whether Firebase client env vars are actually set (not placeholders) */
export function isFirebaseConfigured(): boolean {
  const key = process.env.NEXT_PUBLIC_FIREBASE_API_KEY ?? ''
  const projectId = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID ?? ''
  return (
    key.length > 0 &&
    !key.startsWith('your_') &&
    projectId.length > 0 &&
    !projectId.startsWith('your_')
  )
}
